server:
  port: 8080
  
spring:
  application:
    name: microservices
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/microservices?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: 123456 
